server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userfrom?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver